spring:
  application:
    name: @name@
  profiles:
    active: @profileActive@
  devtools:
    restart:
      enabled: true
logging:
  config: classpath:log4j2-@profileActive@.xml
server:
  port: 80
  http2:
    enabled: true
  undertow:
    worker-threads: 20
    io-threads: 4
    buffer-size: 1024
    direct-buffers: true