package com.sce.data.gaia.mapper.db;

import com.sce.data.gaia.mapper.entity.BiGaiaUsers;

public interface BiGaiaUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_gaia_users
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_gaia_users
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    int insert(BiGaiaUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_gaia_users
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    int insertSelective(BiGaiaUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_gaia_users
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    BiGaiaUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_gaia_users
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    int updateByPrimaryKeySelective(BiGaiaUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_gaia_users
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    int updateByPrimaryKey(BiGaiaUsers record);
}