package com.sce.data.gaia.mapper.entity;

public class BiGaiaUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_gaia_users.id
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_gaia_users.password
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_gaia_users.role_names
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    private String roleNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_gaia_users.user_name
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_gaia_users.id
     *
     * @return the value of bi_gaia_users.id
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_gaia_users.id
     *
     * @param id the value for bi_gaia_users.id
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_gaia_users.password
     *
     * @return the value of bi_gaia_users.password
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_gaia_users.password
     *
     * @param password the value for bi_gaia_users.password
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_gaia_users.role_names
     *
     * @return the value of bi_gaia_users.role_names
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    public String getRoleNames() {
        return roleNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_gaia_users.role_names
     *
     * @param roleNames the value for bi_gaia_users.role_names
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    public void setRoleNames(String roleNames) {
        this.roleNames = roleNames == null ? null : roleNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_gaia_users.user_name
     *
     * @return the value of bi_gaia_users.user_name
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_gaia_users.user_name
     *
     * @param userName the value for bi_gaia_users.user_name
     *
     * @mbggenerated Wed Aug 08 12:52:35 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}